services:
  app:
    container_name: megano
    build:
      dockerfile: .Dockerfile
    command:
      - "poetry"
      - "run"
      - "gunicorn"
      - "backend.megano_.megano_.wsgi:application"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: httl://localhost:3100/loki/api/v1/push
    networks:
      - my_network

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - my_network


  grafana:
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    networks:
      - my_network


  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    networks:
      - my_network


  prometheus:
    image: prom/prometheus:v3.11.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - my_network


networks:
  my_network: