# Generated by Django 6.0.4 on 2026-04-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to='images')),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.SmallIntegerField(default=0)),
                ('count', models.SmallIntegerField(default=1)),
                ('category', models.SmallIntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('fullDescription', models.TextField(blank=True)),
                ('freeDelivery', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.SmallIntegerField(default=0)),
                ('popular_version', models.BooleanField(default=False)),
                ('limited_version', models.BooleanField(default=False)),
                ('salePrice', models.SmallIntegerField(default=0)),
                ('dateForm', models.CharField(max_length=50, null=True)),
                ('dateTo', models.CharField(max_length=50, null=True)),
                ('images', models.ManyToManyField(to='products.imagesmodel')),
                ('specifications', models.ManyToManyField(to='products.specificationsmodel')),
                ('tags', models.ManyToManyField(to='products.tagsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('rate', models.IntegerField(default=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.imagesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.imagesmodel')),
                ('subcategories', models.ManyToManyField(to='products.subcategoriesmodel')),
            ],
        ),
    ]
