# Generated by Django 6.0.4 on 2026-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_options_alter_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
