# Generated by Django 6.0.4 on 2026-04-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='imagesmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='specificationsmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subcategoriesmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tagsmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='categoriesmodel',
            table='product_categories',
        ),
        migrations.AlterModelTable(
            name='imagesmodel',
            table='product_images',
        ),
        migrations.AlterModelTable(
            name='reviewmodel',
            table='product_review',
        ),
        migrations.AlterModelTable(
            name='specificationsmodel',
            table='product_specifications',
        ),
        migrations.AlterModelTable(
            name='subcategoriesmodel',
            table='product_subcategories',
        ),
        migrations.AlterModelTable(
            name='tagsmodel',
            table='product_tags',
        ),
    ]
