# Generated by Django 6.0.4 on 2026-04-11 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
                ('totalCost', models.SmallIntegerField(default=0)),
                ('status', models.CharField(max_length=25)),
                ('deliveryType', models.CharField(max_length=25)),
                ('paymentType', models.CharField(max_length=25)),
                ('products', models.ManyToManyField(to='products.productmodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.profilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
