# Generated by Django 6.0.4 on 2026-04-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_options_alter_ordermodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
    ]
