# Generated by Django 6.0.4 on 2026-04-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='imagemodel',
            table='accounts_avatar',
        ),
        migrations.AlterModelTable(
            name='profilemodel',
            table='accounts_profile',
        ),
    ]
