# Generated by Django 6.0.4 on 2026-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_imagemodel_options_alter_profilemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
