# Generated by Django 6.0.4 on 2026-04-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='basketmodel',
            table='baskets',
        ),
    ]
