# Generated by Django 6.0.4 on 2026-04-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_imagemodel_options_alter_profilemodel_options_and_more'),
        ('basket', '0002_alter_basketmodel_options_alter_basketmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel'),
        ),
    ]
